version: '3.8'

services:
  mongo:
    image: mongo
    container_name: play.catalog.db
    ports:
      - 27017:27017
    networks:
      - learnmicroservices

networks:
  learnmicroservices:
    name: learnmicroservices