@baseUrl = https://localhost:7020

### GET ALL

GET {{baseUrl}}/users

### GET SINGLE
@getSingleId = bba62708-7eab-4a10-8510-9472afeb25f4

sGET {{baseUrl}}/users/{{getSingleId}}

### POST

POST {{baseUrl}}/items
Content-Type: application/json

{
    "name": "item 1",
    "description": "item 1",
    "price": 11
}

### PUT
@updateId = 1ad57678-0229-453e-a089-00cdf9dcef93

PUT {{baseUrl}}/items/{{updateId}}
Content-Type: application/json

{
    "name": "item 1",
    "description": "updated item 1",
    "price": 1
}

### DELETE
@deleteId = id

DELETE {{baseUrl}}/items/{{deleteId}}