@baseUrl = https://localhost:7020

### GET ALL

GET {{baseUrl}}/users

### GET SINGLE
@getSingleId = 63084a3f-60f1-443d-9b21-1d3dd68e10bf

GET {{baseUrl}}/users/{{getSingleId}}

### PUT
@updateUserId = 63084a3f-60f1-443d-9b21-1d3dd68e10bf

PUT {{baseUrl}}/users/{{updateUserId}}
Content-Type: application/json

{
    "email": "klucyszyn1995@gmail.com",
    "gil": 100
}


### DELETE
@deleteId = id

DELETE {{baseUrl}}/items/{{deleteId}}