@baseUrl = https://localhost:7010

### GET ALL USER ITEMS
@userId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

GET {{baseUrl}}/items/{{userId}}


### POST
@grantItemUserId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@grantItemCatalogItemId = {{$guid}}
@grantItemCatalogItemId = fe20dc2b-bc8f-40c5-95fb-83609ac15ee8

POST {{baseUrl}}/items
Content-Type: application/json

{
    "userId": "{{grantItemUserId}}",
    "catalogItemId": "{{grantItemCatalogItemId}}",
    "quantity": 99
}