@baseUrl = https://localhost:7010

### GET ALL USER ITEMS
@userId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

GET {{baseUrl}}/items/{{userId}}


### POST
@grantItemUserId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@grantItemCatalogItemId = {{$guid}}
@grantItemCatalogItemId = 135795ba-4a30-43d0-9d7e-914847896d13

POST {{baseUrl}}/items
Content-Type: application/json

{
    "userId": "{{grantItemUserId}}",
    "catalogItemId": "{{grantItemCatalogItemId}}",
    "quantity": 1
}