@baseUrl = https://localhost:7010

### GET ALL USER ITEMS
@userId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

GET {{baseUrl}}/items/{{userId}}


### POST
@grantItemUserId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@grantItemCatalogItemId = {{$guid}}
@grantItemCatalogItemId = 1ad57678-0229-453e-a089-00cdf9dcef93

POST {{baseUrl}}/items
Content-Type: application/json

{
    "userId": "{{grantItemUserId}}",
    "catalogItemId": "{{grantItemCatalogItemId}}",
    "quantity": 1
}